FROM node:20

WORKDIR /app

RUN corepack enable && corepack prepare yarn@1.22.19 --activate

COPY package.json yarn.lock ./

RUN yarn install --immutable --check-cache

COPY . .

ENV NODE_OPTIONS="--max_old_space_size=1024"
ENV UV_THREADPOOL_SIZE=4

CMD ["yarn", "start"]
