FROM node:20

WORKDIR /app

RUN corepack enable && corepack prepare yarn@1.22.19 --activate

COPY package.json yarn.lock ./
RUN yarn install --immutable --check-cache

COPY . .

CMD ["yarn", "start"]
