export const PLATFORMS_IDS = {
	INSTAGRAM: 1,
	TIKTOK: 2,
};

export const PLATFORMS_NAMES = {
	INSTAGRAM: 'INSTAGRAM',
	TIKTOK: 'TIKTOK',
};

export const PLATFORM_STATUS = {
	ACTIVE: 'ACTIVE',
	PENDING: 'PENDING',
};
